<h2>Importing numpy library that we will be using to manipulate matrices</h2>
<p>NumPy is widely used for numerical computations, providing fast and efficient operations on multi-dimensional arrays and matrices. It is essential for data preprocessing, statistical analysis, and mathematical modeling in machine learning, data science, and scientific computing.</p>

In [2]:
import numpy as np

<h2>Defining vectors and operations on them (summition and multiplying by a scalar) </h2>

In [3]:
# when dealing with only vectors it's okay to define a vector like this
np.array([5, 4, 3, 2])

array([5, 4, 3, 2])

In [4]:
# When defining a vector like in the pervious line it can make problems in eqautions 
# as the shape is not well defined (4, 1)
np.array([5, 4, 3, 2]).shape

(4,)

In [5]:
# you can change the shape of a vector like this
# Notice you need to assgin the result of the reshape to the vector to be saved in place
V = np.array([5,4,3,2])
V = V.reshape((1,4))
V.shape

(1, 4)

In [6]:
# muliplying a vector by a scaler "number"
V * 5

# notice it multiplies each element by 5

array([[25, 20, 15, 10]])

In [7]:
# adding 2 vectors together "Element wise"
V1 = np.array([10, 77, 25, 15])
V2 = np.array([17, 5, 90, 77])

V1 + V2

array([ 27,  82, 115,  92])

In [8]:
# Trying to add 2 vectors that doesn't have the same dimensions
V1 = np.array([10, 77, 25, 15, 33, 60, 11, 5])
V2 = np.array([17, 5, 90, 77, 67])

V1 + V2

# if gives an error if the dimensions are differant

ValueError: operands could not be broadcast together with shapes (8,) (5,) 

<h2>Different ways to intialize a matrix with certain dimensions</h2>

In [9]:
# to specify a 3x3 matrix filled with zeros and of type int
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# to specify a 3x3 matrix but filled with a custom value "7"
np.full((3, 3), 7, dtype=int)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [11]:
# Creating a 3x3 matrix of only ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# defining a 4x4 identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# make a matrix with random numbers from 0 to 10 with dimensions 3x3
np.random.randint(0, 10, size=(3, 3))

array([[8, 8, 4],
       [0, 8, 4],
       [8, 1, 0]])

<h2>Matrix addition is the same as vector addition</h2>

In [14]:
# Element wise addation, so the dimensions of the two matrices must be exact
matrix1 = np.full((3, 3), 7)
matrix2 = np.full((3, 3), 10)

matrix1 + matrix2

array([[17, 17, 17],
       [17, 17, 17],
       [17, 17, 17]])

<h1>Matrix multiplication</h1>

In [15]:
# Element wise multiplication "doesn't have meaning in math"
# not matching exact dimensions here will give an error like the one in the vector as it's element wise
matrix1 = np.full((3, 3), 7)
matrix2 = np.full((3, 3), 10)

matrix1*matrix2

array([[70, 70, 70],
       [70, 70, 70],
       [70, 70, 70]])

In [16]:
# Normal row column multiplication with dot method
matrix1 = np.full((3, 3), 7)
matrix2 = np.full((3, 3), 10)

matrix1.dot(matrix2)

array([[210, 210, 210],
       [210, 210, 210],
       [210, 210, 210]])

In [17]:
# notice if M1 and M2 is (5,3) and (3, 7) we can still multiply them
# the most importatnt thing it number of columns of the first matrix is equal to the number of rows in the second
matrix1 = np.full((5, 3), 7)
matrix2 = np.full((3, 7), 10)

matrix1.dot(matrix2)

array([[210, 210, 210, 210, 210, 210, 210],
       [210, 210, 210, 210, 210, 210, 210],
       [210, 210, 210, 210, 210, 210, 210],
       [210, 210, 210, 210, 210, 210, 210],
       [210, 210, 210, 210, 210, 210, 210]])

In [18]:
# notice that matrix1.dot(matrix2) isn't the same as matrix2.dot(matrix1)
# here dimensions doesn't match (3, 7) . (5, 3) --> order matter
matrix1 = np.full((5, 3), 7)
matrix2 = np.full((3, 7), 10)

matrix2.dot(matrix1)

ValueError: shapes (3,7) and (5,3) not aligned: 7 (dim 1) != 5 (dim 0)

<h2>Multiplication with the identity matrix</h2>

In [19]:
# multiplying with an identity matrix
# notice both the matrix and the I must be of the same square dimensions 
matrix1 = np.identity(3, dtype=int)
matrix2 = np.random.randint(0, 10, size=(3, 3))

print("Before multiplication")
print(matrix2)

print("After multiplication")
print(matrix1.dot(matrix2))

#notice that it doesn't matter if we did matrix1 x matrix2 or matrix2 x matrix1
print("Different order")
print(matrix2.dot(matrix1))

Before multiplication
[[9 4 0]
 [2 2 9]
 [7 1 0]]
After multiplication
[[9 4 0]
 [2 2 9]
 [7 1 0]]
Different order
[[9 4 0]
 [2 2 9]
 [7 1 0]]


<h2>Associativity</h2>